### ISSUE TITLE
Does 'apply_rankselector appear in the code?

### ISSUE THREAD

**Issue by dddfaker** [QingruZhang/AdaLoRA#15]
<img width="405" alt="image" src="https://github.com/QingruZhang/AdaLoRA/assets/50349808/f6738f97-d01c-49c1-af96-b85a46e3e4de">
I can't find this hyperparameter from the code, so how is this parameter used? Thanks!

**Comment by QingruZhang** [comment]
Thanks for your comments. It should be `--apply_adalora`.
