### ISSUE TITLE
from_pretrained parameters

### ISSUE THREAD

**Issue by fxb392** [QingruZhang/AdaLoRA#2]
config = AutoConfig.from_pretrained(
        model_args.config_name if model_args.config_name else model_args.model_name_or_path,
        cache_dir=model_args.cache_dir,
        revision=model_args.model_revision,
        use_auth_token=True if model_args.use_auth_token else None,
        **cls_dropout=training_args.cls_dropout,**
        apply_lora=model_args.apply_lora,
        lora_type=model_args.lora_type, 
        lora_module=model_args.lora_module, 
        lora_alpha=model_args.lora_alpha,
        lora_r=model_args.lora_r,
        apply_adapter=model_args.apply_adapter,
        adapter_type=model_args.adapter_type,
        adapter_size=model_args.adapter_size,
        reg_loss_wgt=model_args.reg_loss_wgt,
        masking_prob=model_args.masking_prob,
    )
what does parameter cls_dropou means? I don't find it in huggingface docs.

**Comment by QingruZhang** [comment]
Hi, this is the dropout probability for deberta model, which is applied in this optimized dropout [module](https://github.com/QingruZhang/AdaLoRA/blob/d10f5ebee16c478fa2f41a44a237b38e8c9b0338/NLU/src/transformers/models/deberta_v2/modeling_deberta_v2.py#L174). The argument is added in [this line](https://github.com/QingruZhang/AdaLoRA/blob/d10f5ebee16c478fa2f41a44a237b38e8c9b0338/NLU/src/transformers/training_args.py#L518). Hope this could answer your question.

**Comment by fxb392** [comment]
ok,thank you.
