### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'rankallocator'

### ISSUE THREAD

**Issue by fxb392** [QingruZhang/AdaLoRA#4]
When initialize the QuestionAnsweringTrainer,i encountered this error.Why the __init__() menth of  QuestionAnsweringTrainer haven't 
self.rankallocator variable ?

error:TypeError: __init__() got an unexpected keyword argument 'rankallocator' #4

>     trainer = QuestionAnsweringTrainer(
>         model=model,
>         args=training_args,
>         train_dataset=train_dataset if training_args.do_train else None,
>         eval_dataset=eval_dataset if training_args.do_eval else None,
>         eval_examples=eval_examples if training_args.do_eval else None,
>         tokenizer=tokenizer,
>         data_collator=data_collator,
>         post_process_function=post_processing_function,
>         compute_metrics=compute_metrics,
>         **rankallocator=rankallocator,**
>         model_args=model_args,
>         tb_writter=tb_writter,
>     )

      

>         class QuestionAnsweringTrainer(Trainer):
>               def __init__(self, *args, eval_examples=None, post_process_function=None, **kwargs):
>                   super().__init__(*args, **kwargs)
>                   self.eval_examples = eval_examples
>                   self.post_process_function = post_process_function

**Comment by fxb392** [comment]
@QingruZhang  The model_args、tb_writer has same problem.

>         rankallocator=rankallocator,
>         model_args=model_args,
>         tb_writter=tb_writter,

**Comment by QingruZhang** [comment]
Hi, please follow the instructions [here](https://github.com/QingruZhang/AdaLoRA/tree/main/NLG_QA#install-the-pre-requisites) to install the dependencies and updated transformers, which contains the [revised trainer definition](https://github.com/QingruZhang/AdaLoRA/blob/d10f5ebee16c478fa2f41a44a237b38e8c9b0338/NLG_QA/src/transformers/trainer.py#L211). Then, you could use the scripts povided in `scripts` folder to run QA tasks. Hope this can answer you question.

**Comment by fxb392** [comment]
Could  you tell me the version of transformer(Trainer) you install? Now i  upgrade the transformer to a latest version=4.30.2 but can 't init the  QuestionAnsweringTrainer. The parent Trainer also haven't rankallocator、rankallocator、tb_writter.

**Comment by fxb392** [comment]
Futhermore,I didn't find the code to add loar for model.

**Comment by QingruZhang** [comment]
Hi, the lora is added by the updated [`transformers`](https://github.com/QingruZhang/AdaLoRA/tree/main/NLG_QA/src/transformers). Thus, you need to install it from the source by running `cd NLG_QA` , `pip install -e .`, which we show by the README therein.

**Comment by fxb392** [comment]
Ok.thanks you a lot ,i  got it .
