### ISSUE TITLE
Tried to run ./scripts/run_debertav3_mnli.sh but received error ""

### ISSUE THREAD

**Issue by ndvbd** [QingruZhang/AdaLoRA#7]
Using this page: https://github.com/QingruZhang/AdaLoRA/tree/main/NLU
Ran the script and received:

Error:
run_glue.py: error: the following arguments are required: --output_dir

**Comment by QingruZhang** [comment]
Hi, could you follow the instruction [here](https://github.com/QingruZhang/AdaLoRA/tree/main/NLU#install-the-pre-requisites) to install the updated transformers package in our repo, e.g., `pip install -e .` ? This may resolve the issue you mentioned. 
Thanks,
Qingru

**Comment by ndvbd** [comment]
Thank you, I did it before I wrote here. I am running from the NLU dir the:
./scripts/run_debertav3_mnli.sh
And get:
run_glue.py: error: the following arguments are required: --output_dir

maybe the output_dir parameter is missing from the .sh script?

**Comment by QingruZhang** [comment]
Could you provide the version and path of installed transformers? I rerun the scripts following the README and they work. Meanwhile, `output_dir` has been modified to `optional` as shown in the [`training_args.py`](https://github.com/QingruZhang/AdaLoRA/blob/d10f5ebee16c478fa2f41a44a237b38e8c9b0338/NLU/src/transformers/training_args.py#L295).
